import { IconType } from "react-icons";
import {
  SiBootstrap,
  SiCplusplus,
  SiCss,
  SiCursor,
  SiDocker,
  SiFastapi,
  SiFlask,
  SiGit,
  SiGnubash,
  SiHtml5,
  SiIntellijidea,
  SiJavascript,
  SiJira,
  SiJupyter,
  SiLangchain,
  SiLinux,
  SiNeo4J,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpencv,
  SiOpenjdk,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiScikitlearn,
  SiSharp,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";
import { TbBrandPowershell, TbBrandVscode } from "react-icons/tb";

export const skillIcons: Record<string, IconType[]> = {
  Python: [SiPython],
  JavaScript: [SiJavascript],
  "C#/C++": [SiSharp, SiCplusplus],
  TypeScript: [SiTypescript],
  Java: [SiOpenjdk],
  "SQL (Postgres)": [SiPostgresql],
  "Cypher (Neo4j)": [SiNeo4J],
  "HTML/CSS": [SiHtml5, SiCss],

  Git: [SiGit],
  "VS Code": [TbBrandVscode],
  Cursor: [SiCursor],
  IntelliJ: [SiIntellijidea],
  Jupyter: [SiJupyter],
  Postman: [SiPostman],
  Jira: [SiJira],
  PowerShell: [TbBrandPowershell],
  Bash: [SiGnubash],
  Linux: [SiLinux],

  Flask: [SiFlask],
  FastAPI: [SiFastapi],
  "Node.js": [SiNodedotjs],
  Bootstrap: [SiBootstrap],
  React: [SiReact],
  "Next.js": [SiNextdotjs],
  "Tailwind CSS": [SiTailwindcss],
  Docker: [SiDocker],
  LangChain: [SiLangchain],
  OpenCV: [SiOpencv],
  Pandas: [SiPandas],
  NumPy: [SiNumpy],
  "scikit-learn": [SiScikitlearn],
};
